### 1. Numpy 属性

In [2]:
import numpy as np

In [13]:
# 列表转换成Numpy识别的矩阵
array = np.array([[1,2,3],
                  [2,3,4]])

In [14]:
print(array)

[[1 2 3]
 [2 3 4]]


In [18]:
# 几维ndim
print('number of dim:',array.ndim)

number of dim: 2


In [16]:
# 形状shape
print('shape',array.shape)

shape (2, 3)


In [17]:
# 元素个数size
print('size',array.size)

size 6


### 2. Numpy 创建array（矩阵/数组）

In [19]:
import numpy as np

In [34]:
# 定义array的type
a = np.array([2,3,3,4], dtype = np.int)

In [35]:
print(a)

[2 3 3 4]


In [36]:
print(a.dtype)

int32


In [39]:
b = np.array([[1,2,3],
                  [2,3,4]])

In [40]:
print(b)

[[1 2 3]
 [2 3 4]]


In [42]:
# 生成0矩阵
c = np.zeros((3,4))
print(c)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [44]:
# 生成1矩阵
d = np.ones((3,4),np.int16)
print(d)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [46]:
# 生成1矩阵
e = np.empty((3,4))
print(e)

[[  1.18575755e-321   0.00000000e+000   0.00000000e+000   0.00000000e+000]
 [  0.00000000e+000   0.00000000e+000   0.00000000e+000   0.00000000e+000]
 [  0.00000000e+000   0.00000000e+000   0.00000000e+000   0.00000000e+000]]


In [48]:
# 生成有序的矩阵
d = np.arange(10,20,2)
print(d)

[10 12 14 16 18]


In [49]:
# 生成一个数列
e = np.arange(12)
print(e)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [50]:
# 重新定义矩阵长和宽
e = np.arange(12).reshape(3,4)
print(e)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [52]:
# 生成线段(分成多少段)
f= np.linspace(1,10,5)
print(f)

[  1.     3.25   5.5    7.75  10.  ]


### 3. Numpy的基础计算

In [57]:
import numpy as np

In [59]:
a = np.array([10,20,30,40])
b = np.arange(4)

In [61]:
# 矩阵加法
c = a + b
print(a,b)
print(c)

[10 20 30 40] [0 1 2 3]
[10 21 32 43]


In [63]:
# array的次方
c = b**3
print(c)

[ 0  1  8 27]


In [66]:
# 三角函数的运算
d = 10 * np.sin(a)
print(d)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [68]:
# 判断array中哪些小于某个数
print(b)
print(b<3)
print(b==3)

[0 1 2 3]
[ True  True  True False]
[False False False  True]


In [69]:
# 矩阵的计算
a = np.array([[1,1],
             [0,1]])
b = np.arange(4).reshape((2,2))

In [71]:
print(a)
print(b)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


In [73]:
# 逐个相乘
c = a * b
print(c)

[[0 1]
 [0 3]]


In [75]:
# 矩阵乘法
c_dot = np.dot(a,b)
print(c_dot)

[[2 4]
 [2 3]]


In [77]:
# 矩阵乘法另一种书写形式
c_dot_2 = a.dot(b)
print(c_dot_2)

[[2 4]
 [2 3]]


In [79]:
# 随机产生从0-1的数字
f =np.random.random((2,4))
print(f)

[[ 0.49775822  0.5475301   0.37398664  0.39374572]
 [ 0.4007054   0.53047494  0.49394144  0.41292337]]


In [82]:
print(f)
print(np.sum(f))
print(np.min(f))
print(np.max(f))

[[ 0.49775822  0.5475301   0.37398664  0.39374572]
 [ 0.4007054   0.53047494  0.49394144  0.41292337]]
3.65106581939
0.373986636905
0.547530096034


In [85]:
# 行或列的最大值或最小值，就要定义它的axis,axis=0列中，axis=1行中
print(np.min(f, axis=0))
print(np.min(f, axis=1))

[ 0.4007054   0.53047494  0.37398664  0.39374572]
[ 0.37398664  0.4007054 ]


### 4. Numpy的基础计算2

In [87]:
import numpy as np

In [89]:
A = np.arange(2,14).reshape((2,6))
print(A)

[[ 2  3  4  5  6  7]
 [ 8  9 10 11 12 13]]


In [91]:
# 打印出最小值、最大值索引
print(np.argmin(A))
print(np.argmax(A))

0
11


In [95]:
# 求整个数列/矩阵的平均值
print(np.mean(A))
print(A.mean())

print(np.average(A))

7.5
7.5
7.5


In [96]:
# 求中位数
print(np.median(A))

7.5


In [102]:
# 累加
print(np.cumsum(A))

# 累差
print(np.diff(A))

# 非零数
print(np.nonzero(A))

# 排序
print(np.sort(A))

[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1 1 1]
 [1 1 1 1 1]]
(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1], dtype=int64), array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5], dtype=int64))
[[ 2  3  4  5  6  7]
 [ 8  9 10 11 12 13]]


In [104]:
# 装置
print(np.transpose(A))
print(A.T)

[[ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]
 [ 7 13]]
[[ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]
 [ 7 13]]


In [105]:
# clip功能，滤波
print(np.clip(A,5,9))

[[5 5 5 5 6 7]
 [8 9 9 9 9 9]]


### 5. Numpy的索引

In [106]:
import numpy as np

In [109]:
A = np.arange(3,15)
print(A)

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [110]:
print(A[3])

6


In [116]:
# 打印出索引值
B = np.arange(3,15).reshape(3,4)
print(B)
print(B[2])
print(B[2][1])
print(B[2,1])

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
12
12


In [119]:
print(B)

# 第三行所有数
print(B[2,:])

# 第三列所有数
print(B[:,2])

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
[ 5  9 13]


In [121]:
print(B[:,1:3])

[[ 4  5]
 [ 8  9]
 [12 13]]


In [123]:
# 打印出每行
for row in B:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [124]:
# 打印出每列（打印出转置后的行）
for column in B.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [127]:
# 打印出每个矩阵的项
print(B)
print(A.flatten())
for item in A.flat:
    print(item)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


### 6. Numpy的array合并

In [128]:
import numpy as np

In [129]:
A = np.array([1,1,1])
B = np.array([2,2,2])
print(A)
print(B)

[1 1 1]
[2 2 2]


In [137]:
# 上下合并、左右合并
C = np.vstack((A,B))  # vertical stack
D = np.hstack((A,B))  # horizontal stack
print(C)
print(D)
print(A.shape,C.shape,D.shape)

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]
(3,) (2, 3) (6,)


In [139]:
# 不能用transport 把一个横向的序列变成一个竖向的序列
print(A.T)

[1 1 1]


In [143]:
# 增加维度，序列变矩阵
print(A[np.newaxis,:])
print(A[:,np.newaxis])
# 或者使用reshape
print(A.reshape(1,3))

[[1 1 1]]
[[1]
 [1]
 [1]]
[[1 1 1]]


### 7. Numpy的array分割

In [145]:
import numpy as np

In [147]:
A = np.arange(12).reshape((3,4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [163]:
# 等量分割
print(np.split(A,2,axis=1))
print(np.split(A,3,axis=0))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [166]:
# 不等量分割
print(np.array_split(A,2,axis=1))
print(np.split(A,[2,1,1],axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([], shape=(3, 0), dtype=int32), array([], shape=(3, 0), dtype=int32), array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])]


In [168]:
print(np.vsplit(A,3)) # vertical split
print(np.hsplit(A,2)) # horizontal split


[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


### 8. Numpy的copy & deep copy

In [169]:
import numpy as np

In [173]:
a = np.arange(4)
print(a)

[0 1 2 3]


In [174]:
b = a
c = a
d = b

In [175]:
a[0] = 11
print(a,b,c,d)

[11  1  2  3] [11  1  2  3] [11  1  2  3] [11  1  2  3]


In [176]:
b is a

True

In [177]:
d[1:3] = [22,33]

In [178]:
print(d,a)

[11 22 33  3] [11 22 33  3]


In [179]:
# copy值，但又不关联，深度copy
b = a.copy()
b

array([11, 22, 33,  3])

In [182]:
a[3] = 44
a

array([11, 22, 33, 44])

In [183]:
b

array([11, 22, 33,  3])

In [ ]:
print(id(A) == id(B))